---
apiVersion: v1
kind: Service
metadata:
  name: demoapi
  namespace: __Release.EnvironmentName__
  labels:
    product: demoapi
spec:
  selector:
    app: demoapi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoapi
  namespace: __Release.EnvironmentName__
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: vtechcicddemo.azurecr.io/cicddemo:__Build.BuildId__
        ports:
        - containerPort: 80
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
